#ifndef CONFIG_H
#define CONFIG_H

#define LINK_COUNT_PER_LEG 2
#define POINT_DESCRIPTION_SIZE 32
#define LEG_DESCRIPTION_SIZE 32

//dog legs config
#define RIGHT_BACK_ORIGIN_X 0
#define RIGHT_BACK_ORIGIN_Y 1
#define RIGHT_BACK_ORIGIN_Z 2
#define RIGHT_BACK_LINK_1_LEN 3
#define RIGHT_BACK_LINK_2_LEN 4

#define RIGHT_FRONT_ORIGIN_X 5
#define RIGHT_FRONT_ORIGIN_Y 6
#define RIGHT_FRONT_ORIGIN_Z 7
#define RIGHT_FRONT_LINK_1_LEN 8
#define RIGHT_FRONT_LINK_2_LEN 9

#define LEFT_BACK_ORIGIN_X 10
#define LEFT_BACK_ORIGIN_Y 11
#define LEFT_BACK_ORIGIN_Z 12
#define LEFT_BACK_LINK_1_LEN 13
#define LEFT_BACK_LINK_2_LEN 14

#define LEFT_FRONT_ORIGIN_X 15
#define LEFT_FRONT_ORIGIN_Y 16
#define LEFT_FRONT_ORIGIN_Z 17
#define LEFT_FRONT_LINK_1_LEN 18
#define LEFT_FRONT_LINK_2_LEN 19

//step profile
#define STAY    "4444"
#define START_PHASES 4
#define START_0 "4333"
#define START_1 "3522"
#define START_2 "2461"
#define START_3 "1357"
#define WALK_PHASES 4
#define WALK_0  "7135"
#define WALK_1  "5713"
#define WALK_2  "3571"
#define WALK_3  "1357"
#define STOP_PHASES 4
#define STOP_0  "4000"
#define STOP_1  "0400"
#define STOP_2  "0040"
#define STOP_3  "0004"

#endif // CONFIG_H
