#ifndef CONFIG_H
#define CONFIG_H

#define LINK_COUNT_PER_LEG 2
#define POINT_DESCRIPTION_SIZE 32
#define LEG_DESCRIPTION_SIZE 32

//dog legs config
#define RIGHT_BACK_ORIGIN_X 0
#define RIGHT_BACK_ORIGIN_Y 1
#define RIGHT_BACK_ORIGIN_Z 2
#define RIGHT_BACK_LINK_1_LEN 3
#define RIGHT_BACK_LINK_2_LEN 4

#define RIGHT_FRONT_ORIGIN_X 5
#define RIGHT_FRONT_ORIGIN_Y 6
#define RIGHT_FRONT_ORIGIN_Z 7
#define RIGHT_FRONT_LINK_1_LEN 8
#define RIGHT_FRONT_LINK_2_LEN 9

#define LEFT_BACK_ORIGIN_X 10
#define LEFT_BACK_ORIGIN_Y 11
#define LEFT_BACK_ORIGIN_Z 12
#define LEFT_BACK_LINK_1_LEN 13
#define LEFT_BACK_LINK_2_LEN 14

#define LEFT_FRONT_ORIGIN_X 15
#define LEFT_FRONT_ORIGIN_Y 16
#define LEFT_FRONT_ORIGIN_Z 17
#define LEFT_FRONT_LINK_1_LEN 18
#define LEFT_FRONT_LINK_2_LEN 19

#endif // CONFIG_H
